-- =====================================================================
--  BOMGUARD  —  PostgreSQL schema for the NPI Files/MSF document tree
--  Source        : <NPI_DATA_DIR>/MSF  (Gen 8/9/10/11, FAI Report Requirement, ...)
--  Target        : PostgreSQL 12+
--
--  MODEL  (disk -> DB)
--    MSF/Gen N                      -> generation  (+ a folder row)
--    MSF/Gen N/<category>/...       -> folder      (every directory, as a tree)
--    .../Gen 8.2_MSF-065963_L11_... -> msf_order   (parsed MSF order folders)
--    every file                     -> file        (the "values")
--
--  NOTES
--    * Data is loaded by BackEnd/scripts/load-bomguard-files.js, which upserts
--      on rel_path, so re-running the loader is safe and keeps history
--      (files gone from disk get is_present = false).
--    * Re-running THIS script drops & recreates the bomguard.* objects
--      (i.e. a full reset). The loader runs it only with --init.
--
--  LOAD
--    node BackEnd/scripts/load-bomguard-files.js --init   -- create + load
--    node BackEnd/scripts/load-bomguard-files.js          -- resync only
--  or manually:
--    psql -h 10.251.231.77 -U te_admin -d annon -f bomguard_postgres.sql
-- =====================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS bomguard;
SET search_path TO bomguard, public;

DROP VIEW  IF EXISTS bomguard.v_part_orders      CASCADE;
DROP VIEW  IF EXISTS bomguard.v_msf_order_files  CASCADE;
DROP TABLE IF EXISTS bomguard.file        CASCADE;
DROP TABLE IF EXISTS bomguard.msf_order   CASCADE;
DROP TABLE IF EXISTS bomguard.folder      CASCADE;
DROP TABLE IF EXISTS bomguard.generation  CASCADE;

-- ---------- generation (Gen 8 / 9 / 10 / 11) ----------
CREATE TABLE bomguard.generation (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gen_number   smallint     NOT NULL UNIQUE,
    folder_name  varchar(50)  NOT NULL,
    rel_path     text         NOT NULL UNIQUE
);
COMMENT ON TABLE bomguard.generation IS 'Top-level "Gen N" folders under MSF.';

-- ---------- folder (every directory, as a tree) ----------
CREATE TABLE bomguard.folder (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id      integer REFERENCES bomguard.folder(id) ON DELETE CASCADE,
    generation_id  integer REFERENCES bomguard.generation(id) ON DELETE CASCADE,
    name           text        NOT NULL,
    rel_path       text        NOT NULL UNIQUE,     -- relative to MSF, '/'-separated
    depth          smallint    NOT NULL,            -- 1 = directly under MSF
    category       text,                            -- first folder under Gen N (e.g. 'Documents', 'Cross table')
    folder_kind    varchar(20) NOT NULL
                   CHECK (folder_kind IN ('generation','category','msf_order','other')),
    is_present     boolean     NOT NULL DEFAULT true,
    first_seen_at  timestamptz NOT NULL DEFAULT now(),
    last_seen_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX folder_parent_idx     ON bomguard.folder(parent_id);
CREATE INDEX folder_generation_idx ON bomguard.folder(generation_id);
COMMENT ON TABLE  bomguard.folder IS 'Every directory under MSF. generation_id is NULL for root-level folders such as "FAI Report Requirement".';
COMMENT ON COLUMN bomguard.folder.category IS 'Folder name directly under Gen N; NULL for the Gen folder itself and root-level folders.';

-- ---------- msf_order (parsed MSF order folders) ----------
CREATE TABLE bomguard.msf_order (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id         integer     NOT NULL UNIQUE REFERENCES bomguard.folder(id) ON DELETE CASCADE,
    parent_order_id   integer     REFERENCES bomguard.msf_order(id) ON DELETE SET NULL,
    msf_number        varchar(20) NOT NULL,          -- e.g. 'MSF-065963'
    gen_version       varchar(10),                   -- e.g. '8.2'
    l11_pn            varchar(30),                   -- e.g. 'M1202868-001'
    l11_pn_suffix     varchar(20),                   -- e.g. '$006'
    l10_pns           text[]      NOT NULL DEFAULT '{}',
    is_dw             boolean     NOT NULL DEFAULT false,
    dw_of_msf_number  varchar(20),                   -- e.g. 'MSF-060977'
    suffix            text                           -- trailing tags: 'AFD', 'JIO', 'S2295', 'EXO', '(HH34)', ...
);
CREATE INDEX msf_order_msf_idx ON bomguard.msf_order(msf_number);
CREATE INDEX msf_order_l11_idx ON bomguard.msf_order(l11_pn);
CREATE INDEX msf_order_dw_idx  ON bomguard.msf_order(dw_of_msf_number);
COMMENT ON TABLE bomguard.msf_order IS 'MSF order folders parsed from names like "Gen 8.2_MSF-065963_L11_M1202868-001_L10_M1202869-001_DW (MSF-060977)".';
COMMENT ON COLUMN bomguard.msf_order.parent_order_id IS 'Set when an order folder is nested inside another order folder.';

-- ---------- file (the values) ----------
CREATE TABLE bomguard.file (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id      integer     REFERENCES bomguard.folder(id) ON DELETE CASCADE,   -- NULL = file directly under MSF
    generation_id  integer     REFERENCES bomguard.generation(id) ON DELETE SET NULL,
    msf_order_id   integer     REFERENCES bomguard.msf_order(id) ON DELETE SET NULL, -- nearest ancestor order folder
    file_name      text        NOT NULL,
    extension      varchar(10),
    rel_path       text        NOT NULL UNIQUE,
    size_bytes     bigint,
    modified_at    timestamptz,
    doc_type       varchar(20) NOT NULL DEFAULT 'other'
                   CHECK (doc_type IN ('bom_master','cable_labeling','cross_table','fai','label_plan','spec','issue_list','other')),
    part_number    varchar(30),                      -- parsed from file name, e.g. 'M1202868-001'
    revision       varchar(10),                      -- parsed from '_RevAJ'
    is_present     boolean     NOT NULL DEFAULT true,
    first_seen_at  timestamptz NOT NULL DEFAULT now(),
    last_seen_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX file_folder_idx    ON bomguard.file(folder_id);
CREATE INDEX file_order_idx     ON bomguard.file(msf_order_id);
CREATE INDEX file_part_idx      ON bomguard.file(part_number);
CREATE INDEX file_doc_type_idx  ON bomguard.file(generation_id, doc_type);
COMMENT ON TABLE bomguard.file IS 'Every file under MSF (NpiLibrary/ and ~$ lock files excluded).';

-- ---------- views ----------
CREATE VIEW bomguard.v_msf_order_files AS
SELECT g.gen_number,
       o.gen_version,
       o.msf_number,
       o.l11_pn,
       o.l10_pns,
       o.is_dw,
       o.dw_of_msf_number,
       fo.name      AS order_folder,
       f.file_name,
       f.doc_type,
       f.part_number,
       f.revision,
       f.size_bytes,
       f.modified_at,
       f.rel_path
FROM bomguard.msf_order o
JOIN bomguard.folder fo      ON fo.id = o.folder_id
LEFT JOIN bomguard.generation g ON g.id = fo.generation_id
LEFT JOIN bomguard.file f    ON f.msf_order_id = o.id AND f.is_present
WHERE fo.is_present;
COMMENT ON VIEW bomguard.v_msf_order_files IS 'MSF order + its files (present only).';

-- One row per (part, order); cross tables of the same generation aggregated.
CREATE VIEW bomguard.v_part_orders AS
WITH part_order AS (
    SELECT o.l11_pn AS part_number, 'L11'::varchar(3) AS level, o.*
    FROM bomguard.msf_order o
    UNION ALL
    SELECT unnest(o.l10_pns), 'L10', o.*
    FROM bomguard.msf_order o
)
SELECT po.part_number,
       po.level,
       po.msf_number,
       po.gen_version,
       po.is_dw,
       po.dw_of_msf_number,
       CASE WHEN po.is_dw THEN 'DW of ' || po.dw_of_msf_number ELSE 'Original' END AS status,
       fo.name AS order_folder,
       g.gen_number,
       (SELECT array_agg(ct.file_name ORDER BY ct.file_name)
          FROM bomguard.file ct
         WHERE ct.generation_id = g.id AND ct.doc_type = 'cross_table' AND ct.is_present) AS cross_tables
FROM part_order po
JOIN bomguard.folder fo      ON fo.id = po.folder_id AND fo.is_present
LEFT JOIN bomguard.generation g ON g.id = fo.generation_id
WHERE po.part_number IS NOT NULL;
COMMENT ON VIEW bomguard.v_part_orders IS 'Part number (L11 or L10) -> linked MSF orders, DW status and the generation''s cross tables.';

COMMIT;
